"""Alert model for pattern detection outputs.

Every alert requires a confidence score (0.0-1.0) and links
back to the entities and sources that generated it.
"""

from datetime import UTC, datetime
from enum import Enum
from typing import Annotated
from uuid import UUID, uuid4

from pydantic import BaseModel, Field


def _utc_now() -> datetime:
    return datetime.now(UTC)


class AlertSeverity(str, Enum):
    """Alert severity levels."""

    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"


class AlertStatus(str, Enum):
    """Alert processing status."""

    NEW = "new"
    ACKNOWLEDGED = "acknowledged"
    INVESTIGATING = "investigating"
    RESOLVED = "resolved"
    DISMISSED = "dismissed"


class AlertType(str, Enum):
    """Types of alerts that detectors can generate."""

    SILENCE = "silence"  # Something stopped happening
    ANOMALY = "anomaly"  # Statistical outlier
    RHYME = "rhyme"  # Pattern that preceded an outcome before
    CASCADE = "cascade"  # Temporal chain of events
    BROKER = "broker"  # Network centrality detection
    COUNTERFACTUAL = "counterfactual"  # Expected vs actual
    VULNERABILITY = "vulnerability"  # CVE/security vulnerability detected
    BREACH = "breach"  # Data breach/credential exposure
    CORPORATE = "corporate"  # SEC filing, corporate announcement
    SECURITY = "security"  # General security events (typosquatting, suspicious certs)
    REGULATORY = "regulatory"  # Federal Register rules, proposed rules, notices
    CONTRACT = "contract"  # Government contract awards from USAspending
    WEATHER = "weather"  # Severe weather alerts


class Alert(BaseModel):
    """An alert generated by a pattern detector.

    Alert IDs use the format "alert:{date}:{seq}".
    """

    id: Annotated[UUID, Field(default_factory=uuid4)]
    alert_type: Annotated[AlertType, Field(description="Type of pattern detected")]
    title: Annotated[str, Field(description="Short alert title")]
    description: Annotated[str, Field(description="Detailed alert description")]
    confidence: Annotated[float, Field(ge=0.0, le=1.0, description="Confidence score (0.0-1.0)")]
    severity: Annotated[AlertSeverity, Field(default=AlertSeverity.MEDIUM)]
    status: Annotated[AlertStatus, Field(default=AlertStatus.NEW)]
    entity_refs: Annotated[list[str], Field(default_factory=list, description="Related entity IDs")]
    source_refs: Annotated[
        list[str], Field(default_factory=list, description="Provenance record IDs")
    ]
    detector_name: Annotated[str, Field(description="Name of detector that generated this")]
    detector_metadata: Annotated[
        dict[str, object],
        Field(default_factory=dict, description="Detector-specific metadata"),
    ]
    narrative: Annotated[str | None, Field(default=None, description="Generated narrative")]
    created_at: Annotated[datetime, Field(default_factory=_utc_now)]
    updated_at: Annotated[datetime, Field(default_factory=_utc_now)]
    acknowledged_at: Annotated[datetime | None, Field(default=None)]
    resolved_at: Annotated[datetime | None, Field(default=None)]

    @property
    def alert_id(self) -> str:
        """Return formatted alert ID."""
        date_str = self.created_at.strftime("%Y%m%d")
        # Use last 4 chars of UUID for sequence
        seq = str(self.id)[-4:]
        return f"alert:{date_str}:{seq}"

    def acknowledge(self) -> None:
        """Mark alert as acknowledged."""
        self.status = AlertStatus.ACKNOWLEDGED
        self.acknowledged_at = _utc_now()
        self.updated_at = _utc_now()

    def resolve(self) -> None:
        """Mark alert as resolved."""
        self.status = AlertStatus.RESOLVED
        self.resolved_at = _utc_now()
        self.updated_at = _utc_now()

    def dismiss(self) -> None:
        """Dismiss the alert."""
        self.status = AlertStatus.DISMISSED
        self.updated_at = _utc_now()

    model_config = {"frozen": False}
