"""Base detector pattern for all Black Box detectors.

All detectors inherit from BaseDetector with a `name` property
and an async `detect()` method.
"""

from abc import ABC, abstractmethod
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from blackbox.models import Activity, Alert, Entity


class BaseDetector(ABC):
    """Abstract base class for pattern detectors.

    Each detector:
    - Has a unique name
    - Implements async detect() method
    - Returns a list of Alert objects with confidence scores
    """

    @property
    @abstractmethod
    def name(self) -> str:
        """Return the unique name of this detector."""
        ...

    @property
    def description(self) -> str:
        """Return a description of what this detector finds."""
        return "No description provided."

    @abstractmethod
    async def detect(
        self,
        entities: list["Entity"],
        activities: list["Activity"] | None = None,
    ) -> list["Alert"]:
        """Run detection on a list of entities.

        Args:
            entities: List of entities to analyze
            activities: Optional list of activities for these entities

        Returns:
            List of alerts generated by this detector.
            Each alert must have a confidence score.
        """
        ...

    async def validate(self) -> bool:
        """Validate that the detector is properly configured.

        Override this method to add custom validation logic.

        Returns:
            True if detector is ready to run, False otherwise.
        """
        return True

    def __repr__(self) -> str:
        return f"<{self.__class__.__name__}(name={self.name!r})>"
